# mysql-pvc-new.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
