# react-pv.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/react
