spring:
  datasource:
    url: jdbc:mysql://mysql-new:3306/todolist
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5175}

jwt:
  secret: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey
  expirationMs: 86400000


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/todolist
#    username: root
#    password: mymysql
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        boot:
#          allow_jdbc_metadata_access: true
#cors:
#  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5175}
#
#jwt:
#  secret: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey
#  expirationMs: 86400000
