# wordpress-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - port: 80 #클러스터 내부에서 서비스가 제공하는 포트입니다.
              #클러스터내의 다른 Pod나 서비스들이 이 포트를 통해 서비스에 접근
      targetPort: 80
      nodePort: 30080
  type: NodePort
