apiVersion: v1
kind: Service
metadata:
  name: my-basic-service
spec:
  selector:
    app: my-basic-pod
  ports:
    - name: http
      port: 81
      targetPort: 5173
      nodePort: 30070
  type: NodePort